title: Cineaste
author: Tolik Pylypcuk
email: pylypchuk.tolik@gmail.com
description: An app for keeping a list of movies and series
avatar: /favicon.ico

baseurl: ""
url: ""

github_username: TolikPylypchuk
repository: TolikPylypchuk/Cineaste

links:
  get-app: https://github.com/TolikPylypchuk/Cineaste/releases
  github: https://github.com/TolikPylypchuk/Cineaste
  view-docs: https://docs.cineaste.tolik.io/

markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
