//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineaste.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cineaste.Client.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string ApiProblemAlert_HideDetails {
            get {
                return ResourceManager.GetString("ApiProblemAlert.HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ApiProblemAlert_ShowDetails {
            get {
                return ResourceManager.GetString("ApiProblemAlert.ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string ApiProblemAlert_TryAgain {
            get {
                return ResourceManager.GetString("ApiProblemAlert.TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cineaste.
        /// </summary>
        public static string Cineaste {
            get {
                return ResourceManager.GetString("Cineaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string CreateListPage_BasicInfo {
            get {
                return ResourceManager.GetString("CreateListPage.BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a List.
        /// </summary>
        public static string CreateListPage_CreateList {
            get {
                return ResourceManager.GetString("CreateListPage.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default titles used when creating new seasons - the # will be replaced with the season number.
        /// </summary>
        public static string CreateListPage_Help_DefaultSeasonTitles {
            get {
                return ResourceManager.GetString("CreateListPage.Help.DefaultSeasonTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list handle is used to identify a list in a URL.
        /// </summary>
        public static string CreateListPage_Help_Handle {
            get {
                return ResourceManager.GetString("CreateListPage.Help.Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title language is used to sort titles in the list correctly.
        /// </summary>
        public static string CreateListPage_Help_TitleLanguage {
            get {
                return ResourceManager.GetString("CreateListPage.Help.TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default season original title.
        /// </summary>
        public static string CreateListPage_List_DefaultSeasonOriginalTitle {
            get {
                return ResourceManager.GetString("CreateListPage.List.DefaultSeasonOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default season title.
        /// </summary>
        public static string CreateListPage_List_DefaultSeasonTitle {
            get {
                return ResourceManager.GetString("CreateListPage.List.DefaultSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string CreateListPage_List_Handle {
            get {
                return ResourceManager.GetString("CreateListPage.List.Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateListPage_List_Name {
            get {
                return ResourceManager.GetString("CreateListPage.List.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Titles.
        /// </summary>
        public static string CreateListPage_List_SeasonTitles {
            get {
                return ResourceManager.GetString("CreateListPage.List.SeasonTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title language.
        /// </summary>
        public static string CreateListPage_List_TitleLanguage {
            get {
                return ResourceManager.GetString("CreateListPage.List.TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the list has failed.
        /// </summary>
        public static string CreateListPage_Problem_CreateList {
            get {
                return ResourceManager.GetString("CreateListPage.Problem.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available languages has failed.
        /// </summary>
        public static string CreateListPage_Problem_Cultures {
            get {
                return ResourceManager.GetString("CreateListPage.Problem.Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a list.
        /// </summary>
        public static string HomePage_CreateList {
            get {
                return ResourceManager.GetString("HomePage.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lists.
        /// </summary>
        public static string HomePage_MyLists {
            get {
                return ResourceManager.GetString("HomePage.MyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lists has failed.
        /// </summary>
        public static string HomePage_Problem_LoadingListsFailed {
            get {
                return ResourceManager.GetString("HomePage.Problem.LoadingListsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new movie.
        /// </summary>
        public static string ListActionsPanel_AddMovie {
            get {
                return ResourceManager.GetString("ListActionsPanel.AddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new series.
        /// </summary>
        public static string ListActionsPanel_AddSeries {
            get {
                return ResourceManager.GetString("ListActionsPanel.AddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string ListPage_Menu_Back {
            get {
                return ResourceManager.GetString("ListPage.Menu.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListPage_Menu_List {
            get {
                return ResourceManager.GetString("ListPage.Menu.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ListPage_Menu_Settings {
            get {
                return ResourceManager.GetString("ListPage.Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list with this handle already exists.
        /// </summary>
        public static string Problem_Conflict_List {
            get {
                return ResourceManager.GetString("Problem.Conflict.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list couldn&apos;t be found - please check that the URL is correct.
        /// </summary>
        public static string Problem_NotFound_List {
            get {
                return ResourceManager.GetString("Problem.NotFound.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string Problem_NotFound_Resource_List {
            get {
                return ResourceManager.GetString("Problem.NotFound.Resource.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown problem has occured.
        /// </summary>
        public static string Problem_Unknown {
            get {
                return ResourceManager.GetString("Problem.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation has failed.
        /// </summary>
        public static string Problem_ValidationFailed {
            get {
                return ResourceManager.GetString("Problem.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list to create is invalid.
        /// </summary>
        public static string Problem_ValidationFailed_CreateList {
            get {
                return ResourceManager.GetString("Problem.ValidationFailed.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is invalid.
        /// </summary>
        public static string Validation_CreateList_Culture_Invalid {
            get {
                return ResourceManager.GetString("Validation.CreateList.Culture.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season original title is empty.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonOriginalTitle_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonOriginalTitle.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season original title is too long.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonOriginalTitle_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonOriginalTitle.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season title is empty.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonTitle_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonTitle.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season title is too long.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonTitle_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonTitle.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is empty.
        /// </summary>
        public static string Validation_CreateList_Name_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.Name.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long.
        /// </summary>
        public static string Validation_CreateList_Name_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.Name.TooLong", resourceCulture);
            }
        }
    }
}
