//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineaste.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cineaste.Client.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide details.
        /// </summary>
        public static string ApiProblemAlert_HideDetails {
            get {
                return ResourceManager.GetString("ApiProblemAlert.HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string ApiProblemAlert_ShowDetails {
            get {
                return ResourceManager.GetString("ApiProblemAlert.ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string ApiProblemAlert_TryAgain {
            get {
                return ResourceManager.GetString("ApiProblemAlert.TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button.Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cineaste.
        /// </summary>
        public static string Cineaste {
            get {
                return ResourceManager.GetString("Cineaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Confirmation_Cancel {
            get {
                return ResourceManager.GetString("Confirmation.Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirmation_Confirm {
            get {
                return ResourceManager.GetString("Confirmation.Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Info.
        /// </summary>
        public static string CreateListPage_BasicInfo {
            get {
                return ResourceManager.GetString("CreateListPage.BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a List.
        /// </summary>
        public static string CreateListPage_CreateList {
            get {
                return ResourceManager.GetString("CreateListPage.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default titles used when creating new seasons - the # will be replaced with the season number.
        /// </summary>
        public static string CreateListPage_Help_DefaultSeasonTitles {
            get {
                return ResourceManager.GetString("CreateListPage.Help.DefaultSeasonTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list handle is used to identify a list in a URL.
        /// </summary>
        public static string CreateListPage_Help_Handle {
            get {
                return ResourceManager.GetString("CreateListPage.Help.Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title language is used to sort titles in the list correctly.
        /// </summary>
        public static string CreateListPage_Help_TitleLanguage {
            get {
                return ResourceManager.GetString("CreateListPage.Help.TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default season original title.
        /// </summary>
        public static string CreateListPage_List_DefaultSeasonOriginalTitle {
            get {
                return ResourceManager.GetString("CreateListPage.List.DefaultSeasonOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default season title.
        /// </summary>
        public static string CreateListPage_List_DefaultSeasonTitle {
            get {
                return ResourceManager.GetString("CreateListPage.List.DefaultSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handle.
        /// </summary>
        public static string CreateListPage_List_Handle {
            get {
                return ResourceManager.GetString("CreateListPage.List.Handle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CreateListPage_List_Name {
            get {
                return ResourceManager.GetString("CreateListPage.List.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Titles.
        /// </summary>
        public static string CreateListPage_List_SeasonTitles {
            get {
                return ResourceManager.GetString("CreateListPage.List.SeasonTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title language.
        /// </summary>
        public static string CreateListPage_List_TitleLanguage {
            get {
                return ResourceManager.GetString("CreateListPage.List.TitleLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the list has failed.
        /// </summary>
        public static string CreateListPage_Problem_CreateList {
            get {
                return ResourceManager.GetString("CreateListPage.Problem.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading available languages has failed.
        /// </summary>
        public static string CreateListPage_Problem_Cultures {
            get {
                return ResourceManager.GetString("CreateListPage.Problem.Cultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a list.
        /// </summary>
        public static string HomePage_CreateList {
            get {
                return ResourceManager.GetString("HomePage.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Lists.
        /// </summary>
        public static string HomePage_MyLists {
            get {
                return ResourceManager.GetString("HomePage.MyLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading lists has failed.
        /// </summary>
        public static string HomePage_Problem_LoadingListsFailed {
            get {
                return ResourceManager.GetString("HomePage.Problem.LoadingListsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb.
        /// </summary>
        public static string Link_Imdb {
            get {
                return ResourceManager.GetString("Link.Imdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.imdb.com/title/{0}.
        /// </summary>
        public static string Link_ImdbUrlFormat {
            get {
                return ResourceManager.GetString("Link.ImdbUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Tomatoes.
        /// </summary>
        public static string Link_RottenTomatoes {
            get {
                return ResourceManager.GetString("Link.RottenTomatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.rottentomatoes.com/{0}.
        /// </summary>
        public static string Link_RottenTomatoesUrlFormat {
            get {
                return ResourceManager.GetString("Link.RottenTomatoesUrlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new movie.
        /// </summary>
        public static string ListActionsPanel_AddMovie {
            get {
                return ResourceManager.GetString("ListActionsPanel.AddMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new series.
        /// </summary>
        public static string ListActionsPanel_AddSeries {
            get {
                return ResourceManager.GetString("ListActionsPanel.AddSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the list has failed.
        /// </summary>
        public static string ListComponent_Problem_LoadingListFailed {
            get {
                return ResourceManager.GetString("ListComponent.Problem.LoadingListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to home page.
        /// </summary>
        public static string ListPage_Menu_Back {
            get {
                return ResourceManager.GetString("ListPage.Menu.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string ListPage_Menu_List {
            get {
                return ResourceManager.GetString("ListPage.Menu.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string ListPage_Menu_Settings {
            get {
                return ResourceManager.GetString("ListPage.Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Month_1 {
            get {
                return ResourceManager.GetString("Month.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Month_10 {
            get {
                return ResourceManager.GetString("Month.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Month_11 {
            get {
                return ResourceManager.GetString("Month.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Month_12 {
            get {
                return ResourceManager.GetString("Month.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Month_2 {
            get {
                return ResourceManager.GetString("Month.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Month_3 {
            get {
                return ResourceManager.GetString("Month.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Month_4 {
            get {
                return ResourceManager.GetString("Month.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Month_5 {
            get {
                return ResourceManager.GetString("Month.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Month_6 {
            get {
                return ResourceManager.GetString("Month.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Month_7 {
            get {
                return ResourceManager.GetString("Month.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Month_8 {
            get {
                return ResourceManager.GetString("Month.8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Month_9 {
            get {
                return ResourceManager.GetString("Month.9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add original title.
        /// </summary>
        public static string MovieForm_AddOriginalTitle {
            get {
                return ResourceManager.GetString("MovieForm.AddOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        public static string MovieForm_AddTitle {
            get {
                return ResourceManager.GetString("MovieForm.AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie created successfully.
        /// </summary>
        public static string MovieForm_CreateMovie_Success {
            get {
                return ResourceManager.GetString("MovieForm.CreateMovie.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this movie?.
        /// </summary>
        public static string MovieForm_DeleteDialog_Body {
            get {
                return ResourceManager.GetString("MovieForm.DeleteDialog.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Movie.
        /// </summary>
        public static string MovieForm_DeleteDialog_Title {
            get {
                return ResourceManager.GetString("MovieForm.DeleteDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb ID.
        /// </summary>
        public static string MovieForm_ImdbId {
            get {
                return ResourceManager.GetString("MovieForm.ImdbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is released.
        /// </summary>
        public static string MovieForm_IsReleased {
            get {
                return ResourceManager.GetString("MovieForm.IsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is watched.
        /// </summary>
        public static string MovieForm_IsWatched {
            get {
                return ResourceManager.GetString("MovieForm.IsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string MovieForm_Kind {
            get {
                return ResourceManager.GetString("MovieForm.Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Movie.
        /// </summary>
        public static string MovieForm_NewMovie {
            get {
                return ResourceManager.GetString("MovieForm.NewMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original titles.
        /// </summary>
        public static string MovieForm_OriginalTitles {
            get {
                return ResourceManager.GetString("MovieForm.OriginalTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the moive has failed.
        /// </summary>
        public static string MovieForm_Problem_CreatingFailed {
            get {
                return ResourceManager.GetString("MovieForm.Problem.CreatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the movie has failed.
        /// </summary>
        public static string MovieForm_Problem_DeletingFailed {
            get {
                return ResourceManager.GetString("MovieForm.Problem.DeletingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the movie has failed.
        /// </summary>
        public static string MovieForm_Problem_LoadingFailed {
            get {
                return ResourceManager.GetString("MovieForm.Problem.LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the movie has failed.
        /// </summary>
        public static string MovieForm_Problem_UpdatingFailed {
            get {
                return ResourceManager.GetString("MovieForm.Problem.UpdatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove original title.
        /// </summary>
        public static string MovieForm_RemoveOriginalTitle {
            get {
                return ResourceManager.GetString("MovieForm.RemoveOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove title.
        /// </summary>
        public static string MovieForm_RemoveTitle {
            get {
                return ResourceManager.GetString("MovieForm.RemoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Tomatoes ID.
        /// </summary>
        public static string MovieForm_RottenTomatoesId {
            get {
                return ResourceManager.GetString("MovieForm.RottenTomatoesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string MovieForm_Titles {
            get {
                return ResourceManager.GetString("MovieForm.Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie updated successfully.
        /// </summary>
        public static string MovieForm_UpdateMovie_Success {
            get {
                return ResourceManager.GetString("MovieForm.UpdateMovie.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string MovieForm_Year {
            get {
                return ResourceManager.GetString("MovieForm.Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End month.
        /// </summary>
        public static string PeriodForm_EndMonth {
            get {
                return ResourceManager.GetString("PeriodForm.EndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End year.
        /// </summary>
        public static string PeriodForm_EndYear {
            get {
                return ResourceManager.GetString("PeriodForm.EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of episodes.
        /// </summary>
        public static string PeriodForm_EpisodeCount {
            get {
                return ResourceManager.GetString("PeriodForm.EpisodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is single-day release.
        /// </summary>
        public static string PeriodForm_IsSingleDayRelease {
            get {
                return ResourceManager.GetString("PeriodForm.IsSingleDayRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release month.
        /// </summary>
        public static string PeriodForm_ReleaseMonth {
            get {
                return ResourceManager.GetString("PeriodForm.ReleaseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year.
        /// </summary>
        public static string PeriodForm_ReleaseYear {
            get {
                return ResourceManager.GetString("PeriodForm.ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Tomatoes ID.
        /// </summary>
        public static string PeriodForm_RottenTomatoesId {
            get {
                return ResourceManager.GetString("PeriodForm.RottenTomatoesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start month.
        /// </summary>
        public static string PeriodForm_StartMonth {
            get {
                return ResourceManager.GetString("PeriodForm.StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start year.
        /// </summary>
        public static string PeriodForm_StartYear {
            get {
                return ResourceManager.GetString("PeriodForm.StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list with this handle already exists.
        /// </summary>
        public static string Problem_Conflict_List {
            get {
                return ResourceManager.GetString("Problem.Conflict.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource couldn&apos;t be found.
        /// </summary>
        public static string Problem_NotFound_Any {
            get {
                return ResourceManager.GetString("Problem.NotFound.Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list couldn&apos;t be found - please check that the URL is correct.
        /// </summary>
        public static string Problem_NotFound_List {
            get {
                return ResourceManager.GetString("Problem.NotFound.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The movie couldn&apos;t be found.
        /// </summary>
        public static string Problem_NotFound_Movie {
            get {
                return ResourceManager.GetString("Problem.NotFound.Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to any.
        /// </summary>
        public static string Problem_NotFound_Resource_Any {
            get {
                return ResourceManager.GetString("Problem.NotFound.Resource.Any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        public static string Problem_NotFound_Resource_List {
            get {
                return ResourceManager.GetString("Problem.NotFound.Resource.List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to movie.
        /// </summary>
        public static string Problem_NotFound_Resource_Movie {
            get {
                return ResourceManager.GetString("Problem.NotFound.Resource.Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The series couldn&apos;t be found.
        /// </summary>
        public static string Problem_NotFound_Series {
            get {
                return ResourceManager.GetString("Problem.NotFound.Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown problem has occured.
        /// </summary>
        public static string Problem_Unknown {
            get {
                return ResourceManager.GetString("Problem.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation has failed.
        /// </summary>
        public static string Problem_ValidationFailed {
            get {
                return ResourceManager.GetString("Problem.ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list to create is invalid.
        /// </summary>
        public static string Problem_ValidationFailed_CreateList {
            get {
                return ResourceManager.GetString("Problem.ValidationFailed.CreateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add original title.
        /// </summary>
        public static string SeasonForm_AddOriginalTitle {
            get {
                return ResourceManager.GetString("SeasonForm.AddOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add period.
        /// </summary>
        public static string SeasonForm_AddPeriod {
            get {
                return ResourceManager.GetString("SeasonForm.AddPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        public static string SeasonForm_AddTitle {
            get {
                return ResourceManager.GetString("SeasonForm.AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        public static string SeasonForm_Channel {
            get {
                return ResourceManager.GetString("SeasonForm.Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to series.
        /// </summary>
        public static string SeasonForm_GoToSeries {
            get {
                return ResourceManager.GetString("SeasonForm.GoToSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original titles.
        /// </summary>
        public static string SeasonForm_OriginalTitles {
            get {
                return ResourceManager.GetString("SeasonForm.OriginalTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release status.
        /// </summary>
        public static string SeasonForm_ReleaseStatus {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string SeasonForm_ReleaseStatus_Finished {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus.Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiatus.
        /// </summary>
        public static string SeasonForm_ReleaseStatus_Hiatus {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus.Hiatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string SeasonForm_ReleaseStatus_NotStarted {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus.NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string SeasonForm_ReleaseStatus_Running {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t care.
        /// </summary>
        public static string SeasonForm_ReleaseStatus_Unknown {
            get {
                return ResourceManager.GetString("SeasonForm.ReleaseStatus.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string SeasonForm_Titles {
            get {
                return ResourceManager.GetString("SeasonForm.Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch status.
        /// </summary>
        public static string SeasonForm_WatchStatus {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiatus.
        /// </summary>
        public static string SeasonForm_WatchStatus_Hiatus {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus.Hiatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not watched.
        /// </summary>
        public static string SeasonForm_WatchStatus_NotWatched {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus.NotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped watching.
        /// </summary>
        public static string SeasonForm_WatchStatus_StoppedWatching {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus.StoppedWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string SeasonForm_WatchStatus_Watched {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus.Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        public static string SeasonForm_WatchStatus_Watching {
            get {
                return ResourceManager.GetString("SeasonForm.WatchStatus.Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add original title.
        /// </summary>
        public static string SeriesForm_AddOriginalTitle {
            get {
                return ResourceManager.GetString("SeriesForm.AddOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add season.
        /// </summary>
        public static string SeriesForm_AddSeason {
            get {
                return ResourceManager.GetString("SeriesForm.AddSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add special episode.
        /// </summary>
        public static string SeriesForm_AddSpecialEpisode {
            get {
                return ResourceManager.GetString("SeriesForm.AddSpecialEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        public static string SeriesForm_AddTitle {
            get {
                return ResourceManager.GetString("SeriesForm.AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string SeriesForm_Component_MoveDown {
            get {
                return ResourceManager.GetString("SeriesForm.Component.MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string SeriesForm_Component_MoveUp {
            get {
                return ResourceManager.GetString("SeriesForm.Component.MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this series?.
        /// </summary>
        public static string SeriesForm_DeleteDialog_Body {
            get {
                return ResourceManager.GetString("SeriesForm.DeleteDialog.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Series.
        /// </summary>
        public static string SeriesForm_DeleteDialog_Title {
            get {
                return ResourceManager.GetString("SeriesForm.DeleteDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb ID.
        /// </summary>
        public static string SeriesForm_ImdbId {
            get {
                return ResourceManager.GetString("SeriesForm.ImdbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        public static string SeriesForm_Kind {
            get {
                return ResourceManager.GetString("SeriesForm.Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Series.
        /// </summary>
        public static string SeriesForm_NewSeries {
            get {
                return ResourceManager.GetString("SeriesForm.NewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original titles.
        /// </summary>
        public static string SeriesForm_OriginalTitles {
            get {
                return ResourceManager.GetString("SeriesForm.OriginalTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the series has failed.
        /// </summary>
        public static string SeriesForm_Problem_CreatingFailed {
            get {
                return ResourceManager.GetString("SeriesForm.Problem.CreatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the series has failed.
        /// </summary>
        public static string SeriesForm_Problem_DeletingFailed {
            get {
                return ResourceManager.GetString("SeriesForm.Problem.DeletingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading the series has failed.
        /// </summary>
        public static string SeriesForm_Problem_LoadingFailed {
            get {
                return ResourceManager.GetString("SeriesForm.Problem.LoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the series has failed.
        /// </summary>
        public static string SeriesForm_Problem_UpdatingFailed {
            get {
                return ResourceManager.GetString("SeriesForm.Problem.UpdatingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release status.
        /// </summary>
        public static string SeriesForm_ReleaseStatus {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_Cancelled {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_Finished {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiatus.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_Hiatus {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.Hiatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_NotStarted {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_Running {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t care.
        /// </summary>
        public static string SeriesForm_ReleaseStatus_Unknown {
            get {
                return ResourceManager.GetString("SeriesForm.ReleaseStatus.Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Tomatoes ID.
        /// </summary>
        public static string SeriesForm_RottenTomatoesId {
            get {
                return ResourceManager.GetString("SeriesForm.RottenTomatoesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string SeriesForm_Titles {
            get {
                return ResourceManager.GetString("SeriesForm.Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch status.
        /// </summary>
        public static string SeriesForm_WatchStatus {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiatus.
        /// </summary>
        public static string SeriesForm_WatchStatus_Hiatus {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus.Hiatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not watched.
        /// </summary>
        public static string SeriesForm_WatchStatus_NotWatched {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus.NotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped watching.
        /// </summary>
        public static string SeriesForm_WatchStatus_StoppedWatching {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus.StoppedWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched.
        /// </summary>
        public static string SeriesForm_WatchStatus_Watched {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus.Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching.
        /// </summary>
        public static string SeriesForm_WatchStatus_Watching {
            get {
                return ResourceManager.GetString("SeriesForm.WatchStatus.Watching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add original title.
        /// </summary>
        public static string SpecialEpisodeForm_AddOriginalTitle {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.AddOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add title.
        /// </summary>
        public static string SpecialEpisodeForm_AddTitle {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.AddTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chanel.
        /// </summary>
        public static string SpecialEpisodeForm_Channel {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to series.
        /// </summary>
        public static string SpecialEpisodeForm_GoToSeries {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.GoToSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Special Episode.
        /// </summary>
        public static string SpecialEpisodeForm_NewSpecialEpisode {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.NewSpecialEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original titles.
        /// </summary>
        public static string SpecialEpisodeForm_OriginalTitles {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.OriginalTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release month.
        /// </summary>
        public static string SpecialEpisodeForm_ReleaseMonth {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.ReleaseMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year.
        /// </summary>
        public static string SpecialEpisodeForm_ReleaseYear {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotten Tomatoes ID.
        /// </summary>
        public static string SpecialEpisodeForm_RottenTomatoesId {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.RottenTomatoesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titles.
        /// </summary>
        public static string SpecialEpisodeForm_Titles {
            get {
                return ResourceManager.GetString("SpecialEpisodeForm.Titles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is released.
        /// </summary>
        public static string SpeicalEpisodeForm_IsReleased {
            get {
                return ResourceManager.GetString("SpeicalEpisodeForm.IsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is watched.
        /// </summary>
        public static string SpeicalEpisodeForm_IsWatched {
            get {
                return ResourceManager.GetString("SpeicalEpisodeForm.IsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language is invalid.
        /// </summary>
        public static string Validation_CreateList_Culture_Invalid {
            get {
                return ResourceManager.GetString("Validation.CreateList.Culture.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season original title is empty.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonOriginalTitle_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonOriginalTitle.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season original title is too long.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonOriginalTitle_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonOriginalTitle.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season title is empty.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonTitle_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonTitle.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default season title is too long.
        /// </summary>
        public static string Validation_CreateList_DefaultSeasonTitle_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.DefaultSeasonTitle.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is empty.
        /// </summary>
        public static string Validation_CreateList_Name_Empty {
            get {
                return ResourceManager.GetString("Validation.CreateList.Name.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is too long.
        /// </summary>
        public static string Validation_CreateList_Name_TooLong {
            get {
                return ResourceManager.GetString("Validation.CreateList.Name.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IMDb ID must be in the form &apos;tt[digits]&apos; e.g. &apos;tt123456&apos;.
        /// </summary>
        public static string Validation_Movie_ImdbId_Invalid {
            get {
                return ResourceManager.GetString("Validation.Movie.ImdbId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release value is invalid.
        /// </summary>
        public static string Validation_Movie_IsReleased_Invalid {
            get {
                return ResourceManager.GetString("Validation.Movie.IsReleased.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-released movie cannot be watched.
        /// </summary>
        public static string Validation_Movie_IsWatched_Invalid {
            get {
                return ResourceManager.GetString("Validation.Movie.IsWatched.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original titles must all be different.
        /// </summary>
        public static string Validation_Movie_OriginalTitles_Distinct_Names {
            get {
                return ResourceManager.GetString("Validation.Movie.OriginalTitles.Distinct.Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rotten Tomatoes ID must start with &apos;m/&apos; or &apos;tv/&apos;.
        /// </summary>
        public static string Validation_Movie_RottenTomatoesId_Invalid {
            get {
                return ResourceManager.GetString("Validation.Movie.RottenTomatoesId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The titles must all be different.
        /// </summary>
        public static string Validation_Movie_Titles_Distinct_Names {
            get {
                return ResourceManager.GetString("Validation.Movie.Titles.Distinct.Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year must be after 1900.
        /// </summary>
        public static string Validation_Movie_Year_TooLow {
            get {
                return ResourceManager.GetString("Validation.Movie.Year.TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end month is invalid.
        /// </summary>
        public static string Validation_Period_EndMonth_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.EndMonth.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end year must be after 1900.
        /// </summary>
        public static string Validation_Period_EndYear_TooLow {
            get {
                return ResourceManager.GetString("Validation.Period.EndYear.TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The episode count is invalid.
        /// </summary>
        public static string Validation_Period_EpisodeCount_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.EpisodeCount.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period is invalid.
        /// </summary>
        public static string Validation_Period_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start and end dates must be the same.
        /// </summary>
        public static string Validation_Period_IsSingleDayRelease_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.IsSingleDayRelease.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The period must be a single-day release.
        /// </summary>
        public static string Validation_Period_IsSingleDayRelease_MustBeTrue {
            get {
                return ResourceManager.GetString("Validation.Period.IsSingleDayRelease.MustBeTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rotten Tomatoes ID must start with &apos;m/&apos; or &apos;tv/&apos;.
        /// </summary>
        public static string Validation_Period_RottenTomatoesId_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.RottenTomatoesId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start month is invalid.
        /// </summary>
        public static string Validation_Period_StartMonth_Invalid {
            get {
                return ResourceManager.GetString("Validation.Period.StartMonth.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start year must be after 1900.
        /// </summary>
        public static string Validation_Period_StartYear_TooLow {
            get {
                return ResourceManager.GetString("Validation.Period.StartYear.TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel is empty.
        /// </summary>
        public static string Validation_Season_Channel_Empty {
            get {
                return ResourceManager.GetString("Validation.Season.Channel.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel is too long.
        /// </summary>
        public static string Validation_Season_Channel_TooLong {
            get {
                return ResourceManager.GetString("Validation.Season.Channel.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The periods are absent.
        /// </summary>
        public static string Validation_Season_Periods_Empty {
            get {
                return ResourceManager.GetString("Validation.Season.Periods.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The periods must not overlap.
        /// </summary>
        public static string Validation_Season_Periods_Overlap {
            get {
                return ResourceManager.GetString("Validation.Season.Periods.Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release status is invalid.
        /// </summary>
        public static string Validation_Season_ReleaseStatus_Invalid {
            get {
                return ResourceManager.GetString("Validation.Season.ReleaseStatus.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The titles must all be different.
        /// </summary>
        public static string Validation_Season_Titles_Distinct_Names {
            get {
                return ResourceManager.GetString("Validation.Season.Titles.Distinct.Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watch status is invalid.
        /// </summary>
        public static string Validation_Season_WatchStatus_Invalid {
            get {
                return ResourceManager.GetString("Validation.Season.WatchStatus.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IMDb ID must be in the form &apos;tt[digits]&apos; e.g. &apos;tt123456&apos;.
        /// </summary>
        public static string Validation_Series_ImdbId_Invalid {
            get {
                return ResourceManager.GetString("Validation.Series.ImdbId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A miniseries must only contain one season with one period.
        /// </summary>
        public static string Validation_Series_IsMiniseries_Invalid {
            get {
                return ResourceManager.GetString("Validation.Series.IsMiniseries.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release status is invalid.
        /// </summary>
        public static string Validation_Series_ReleaseStatus_Invalid {
            get {
                return ResourceManager.GetString("Validation.Series.ReleaseStatus.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rotten Tomatoes ID must start with &apos;m/&apos; or &apos;tv/&apos;.
        /// </summary>
        public static string Validation_Series_RottenTomatoesId_Invalid {
            get {
                return ResourceManager.GetString("Validation.Series.RottenTomatoesId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one season.
        /// </summary>
        public static string Validation_Series_Seasons_Empty {
            get {
                return ResourceManager.GetString("Validation.Series.Seasons.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The watch status is invalid.
        /// </summary>
        public static string Validation_Series_WatchStatus_Invalid {
            get {
                return ResourceManager.GetString("Validation.Series.WatchStatus.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel is empty.
        /// </summary>
        public static string Validation_SpecialEpisode_Channel_Empty {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.Channel.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The channel is too long.
        /// </summary>
        public static string Validation_SpecialEpisode_Channel_TooLong {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.Channel.TooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The release value is invalid.
        /// </summary>
        public static string Validation_SpecialEpisode_IsReleased_Invalid {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.IsReleased.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-released episode cannot be watched.
        /// </summary>
        public static string Validation_SpecialEpisode_IsWatched_Invalid {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.IsWatched.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The month is invalid.
        /// </summary>
        public static string Validation_SpecialEpisode_Month_Invalid {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.Month.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Rotten Tomatoes ID must start with &apos;m/&apos; or &apos;tv/&apos;.
        /// </summary>
        public static string Validation_SpecialEpisode_RottenTomatoesId_Invalid {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.RottenTomatoesId.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The year is too low.
        /// </summary>
        public static string Validation_SpecialEpisode_Year_TooLow {
            get {
                return ResourceManager.GetString("Validation.SpecialEpisode.Year.TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is empty.
        /// </summary>
        public static string Validation_Title_Name_Empty {
            get {
                return ResourceManager.GetString("Validation.Title.Name.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title is too long.
        /// </summary>
        public static string Validation_Title_Name_TooLong {
            get {
                return ResourceManager.GetString("Validation.Title.Name.TooLong", resourceCulture);
            }
        }
    }
}
