//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieList.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string AddIcon {
            get {
                return ResourceManager.GetString("AddIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розширені налаштування.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розширені.
        /// </summary>
        public static string ColorPickerAdvanced {
            get {
                return ResourceManager.GetString("ColorPickerAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступні кольори.
        /// </summary>
        public static string ColorPickerAvailableColors {
            get {
                return ResourceManager.GetString("ColorPickerAvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавно використані кольори.
        /// </summary>
        public static string ColorPickerRecentColors {
            get {
                return ResourceManager.GetString("ColorPickerRecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартні.
        /// </summary>
        public static string ColorPickerStandard {
            get {
                return ResourceManager.GetString("ColorPickerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартні кольори.
        /// </summary>
        public static string ColorPickerStandardColors {
            get {
                return ResourceManager.GetString("ColorPickerStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях до бази даних.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string DefaultSeasonNumberPlaceholder {
            get {
                return ResourceManager.GetString("DefaultSeasonNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна оригінальна назва сезону.
        /// </summary>
        public static string DefaultSeasonOriginalTitle {
            get {
                return ResourceManager.GetString("DefaultSeasonOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна назва сезону.
        /// </summary>
        public static string DefaultSeasonTitle {
            get {
                return ResourceManager.GetString("DefaultSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна назва сезону має містити знак #.
        /// </summary>
        public static string DefaultSeasonTitleInvalid {
            get {
                return ResourceManager.GetString("DefaultSeasonTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях не є назвою файлу.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можна видалити вид, оскільки є фільми чи серіали цього виду..
        /// </summary>
        public static string KindIsInUse {
            get {
                return ResourceManager.GetString("KindIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Види фільмів та серіалів.
        /// </summary>
        public static string Kinds {
            get {
                return ResourceManager.GetString("Kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string ListItemNumber {
            get {
                return ResourceManager.GetString("ListItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригінальна назва.
        /// </summary>
        public static string ListItemOriginalTitle {
            get {
                return ResourceManager.GetString("ListItemOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва українською.
        /// </summary>
        public static string ListItemTitle {
            get {
                return ResourceManager.GetString("ListItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік.
        /// </summary>
        public static string ListItemYear {
            get {
                return ResourceManager.GetString("ListItemYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільм.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва не може бути порожньою.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий вид.
        /// </summary>
        public static string NewKind {
            get {
                return ResourceManager.GetString("NewKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майбутній.
        /// </summary>
        public static string NotReleased {
            get {
                return ResourceManager.GetString("NotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не переглянутий.
        /// </summary>
        public static string NotWatched {
            get {
                return ResourceManager.GetString("NotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші налаштування.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ×.
        /// </summary>
        public static string RemoveIcon {
            get {
                return ResourceManager.GetString("RemoveIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зберегти налаштування..
        /// </summary>
        public static string SavingSettingsFailed {
            get {
                return ResourceManager.GetString("SavingSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серіал.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільми і серіали.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути лог.
        /// </summary>
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
    }
}
