//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieList.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieList.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати фільм.
        /// </summary>
        public static string AddNewMovie {
            get {
                return ResourceManager.GetString("AddNewMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати сезон.
        /// </summary>
        public static string AddNewSeason {
            get {
                return ResourceManager.GetString("AddNewSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати серіал.
        /// </summary>
        public static string AddNewSeries {
            get {
                return ResourceManager.GetString("AddNewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати спеціальну серію.
        /// </summary>
        public static string AddNewSpecialEpisode {
            get {
                return ResourceManager.GetString("AddNewSpecialEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розширені налаштування.
        /// </summary>
        public static string AdvancedSettings {
            get {
                return ResourceManager.GetString("AdvancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квітень.
        /// </summary>
        public static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серпень.
        /// </summary>
        public static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасувати.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал.
        /// </summary>
        public static string Channel {
            get {
                return ResourceManager.GetString("Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Канал є обов&apos;язковим.
        /// </summary>
        public static string ChannelRequired {
            get {
                return ResourceManager.GetString("ChannelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Розширені.
        /// </summary>
        public static string ColorPickerAdvanced {
            get {
                return ResourceManager.GetString("ColorPickerAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступні кольори.
        /// </summary>
        public static string ColorPickerAvailableColors {
            get {
                return ResourceManager.GetString("ColorPickerAvailableColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недавно використані кольори.
        /// </summary>
        public static string ColorPickerRecentColors {
            get {
                return ResourceManager.GetString("ColorPickerRecentColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартні.
        /// </summary>
        public static string ColorPickerStandard {
            get {
                return ResourceManager.GetString("ColorPickerStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартні кольори.
        /// </summary>
        public static string ColorPickerStandardColors {
            get {
                return ResourceManager.GetString("ColorPickerStandardColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях до бази даних.
        /// </summary>
        public static string DatabasePath {
            get {
                return ResourceManager.GetString("DatabasePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях до бази даних є обов&apos;язковим.
        /// </summary>
        public static string DatabasePathRequired {
            get {
                return ResourceManager.GetString("DatabasePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Грудень.
        /// </summary>
        public static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        public static string DefaultSeasonNumberPlaceholder {
            get {
                return ResourceManager.GetString("DefaultSeasonNumberPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна оригінальна назва сезону.
        /// </summary>
        public static string DefaultSeasonOriginalTitle {
            get {
                return ResourceManager.GetString("DefaultSeasonOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна назва сезону.
        /// </summary>
        public static string DefaultSeasonTitle {
            get {
                return ResourceManager.GetString("DefaultSeasonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стандартна назва сезону має містити знак #.
        /// </summary>
        public static string DefaultSeasonTitleInvalid {
            get {
                return ResourceManager.GetString("DefaultSeasonTitleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цей фільм?.
        /// </summary>
        public static string DeleteMoviePrompt {
            get {
                return ResourceManager.GetString("DeleteMoviePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цей сезон?.
        /// </summary>
        public static string DeleteSeasonPrompt {
            get {
                return ResourceManager.GetString("DeleteSeasonPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цей серіал?.
        /// </summary>
        public static string DeleteSeriesPrompt {
            get {
                return ResourceManager.GetString("DeleteSeriesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно хочете видалити цю серію?.
        /// </summary>
        public static string DeleteSpecialEpisodePrompt {
            get {
                return ResourceManager.GetString("DeleteSpecialEpisodePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кінець.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місяць кінця.
        /// </summary>
        public static string EndMonth {
            get {
                return ResourceManager.GetString("EndMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік кінця.
        /// </summary>
        public static string EndYear {
            get {
                return ResourceManager.GetString("EndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майбутня.
        /// </summary>
        public static string EpisodeNotReleased {
            get {
                return ResourceManager.GetString("EpisodeNotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянута.
        /// </summary>
        public static string EpisodeWatched {
            get {
                return ResourceManager.GetString("EpisodeWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лютий.
        /// </summary>
        public static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMDb.
        /// </summary>
        public static string Imdb {
            get {
                return ResourceManager.GetString("Imdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на IMDb має бути URL.
        /// </summary>
        public static string InvalidImdbLink {
            get {
                return ResourceManager.GetString("InvalidImdbLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильне число.
        /// </summary>
        public static string InvalidNumberOfEpisodes {
            get {
                return ResourceManager.GetString("InvalidNumberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шлях не є назвою файлу.
        /// </summary>
        public static string InvalidPath {
            get {
                return ResourceManager.GetString("InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на постер має бути URL.
        /// </summary>
        public static string InvalidPosterUrl {
            get {
                return ResourceManager.GetString("InvalidPosterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильний рік.
        /// </summary>
        public static string InvalidYear {
            get {
                return ResourceManager.GetString("InvalidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Січень.
        /// </summary>
        public static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Липень.
        /// </summary>
        public static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Червень.
        /// </summary>
        public static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вид.
        /// </summary>
        public static string Kind {
            get {
                return ResourceManager.GetString("Kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не можна видалити вид, оскільки є фільми чи серіали цього виду..
        /// </summary>
        public static string KindIsInUse {
            get {
                return ResourceManager.GetString("KindIsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Види фільмів та серіалів.
        /// </summary>
        public static string Kinds {
            get {
                return ResourceManager.GetString("Kinds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        public static string ListItemNumber {
            get {
                return ResourceManager.GetString("ListItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригінальна назва.
        /// </summary>
        public static string ListItemOriginalTitle {
            get {
                return ResourceManager.GetString("ListItemOriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва українською.
        /// </summary>
        public static string ListItemTitle {
            get {
                return ResourceManager.GetString("ListItemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік.
        /// </summary>
        public static string ListItemYear {
            get {
                return ResourceManager.GetString("ListItemYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Березень.
        /// </summary>
        public static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити як майбутній.
        /// </summary>
        public static string MarkAsNotReleased {
            get {
                return ResourceManager.GetString("MarkAsNotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити як не переглянутий.
        /// </summary>
        public static string MarkAsNotWatched {
            get {
                return ResourceManager.GetString("MarkAsNotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити як не майбутній.
        /// </summary>
        public static string MarkAsReleased {
            get {
                return ResourceManager.GetString("MarkAsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Позначити як переглянутий.
        /// </summary>
        public static string MarkAsWatched {
            get {
                return ResourceManager.GetString("MarkAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Травень.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мінісеріал.
        /// </summary>
        public static string Miniseries {
            get {
                return ResourceManager.GetString("Miniseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місяць.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільм.
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва є обов&apos;язковою.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий вид.
        /// </summary>
        public static string NewKind {
            get {
                return ResourceManager.GetString("NewKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий фільм.
        /// </summary>
        public static string NewMovie {
            get {
                return ResourceManager.GetString("NewMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий серіал.
        /// </summary>
        public static string NewSeries {
            get {
                return ResourceManager.GetString("NewSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова спеціальна серія.
        /// </summary>
        public static string NewSpecialEpisode {
            get {
                return ResourceManager.GetString("NewSpecialEpisode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майбутній.
        /// </summary>
        public static string NotReleased {
            get {
                return ResourceManager.GetString("NotReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не переглянутий.
        /// </summary>
        public static string NotWatched {
            get {
                return ResourceManager.GetString("NotWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Листопад.
        /// </summary>
        public static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кількість серій.
        /// </summary>
        public static string NumberOfEpisodes {
            get {
                return ResourceManager.GetString("NumberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обов&apos;язкове.
        /// </summary>
        public static string NumberOfEpisodesRequired {
            get {
                return ResourceManager.GetString("NumberOfEpisodesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жовтень.
        /// </summary>
        public static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оригінальна назва.
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інші налаштування.
        /// </summary>
        public static string OtherSettings {
            get {
                return ResourceManager.GetString("OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Періоди.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Посилання на постер.
        /// </summary>
        public static string PosterUrl {
            get {
                return ResourceManager.GetString("PosterUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реліз.
        /// </summary>
        public static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося зберегти налаштування..
        /// </summary>
        public static string SavingSettingsFailed {
            get {
                return ResourceManager.GetString("SavingSettingsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сезони.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вересень.
        /// </summary>
        public static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серіал.
        /// </summary>
        public static string Series {
            get {
                return ResourceManager.GetString("Series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скасований.
        /// </summary>
        public static string SeriesCancelled {
            get {
                return ResourceManager.GetString("SeriesCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершений.
        /// </summary>
        public static string SeriesFinished {
            get {
                return ResourceManager.GetString("SeriesFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не розпочатий.
        /// </summary>
        public static string SeriesNotStarted {
            get {
                return ResourceManager.GetString("SeriesNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Триває.
        /// </summary>
        public static string SeriesRunning {
            get {
                return ResourceManager.GetString("SeriesRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string SeriesStatus {
            get {
                return ResourceManager.GetString("SeriesStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Налаштування.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реліз в один день.
        /// </summary>
        public static string SingleDayRelease {
            get {
                return ResourceManager.GetString("SingleDayRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Початок.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Місяць початку.
        /// </summary>
        public static string StartMonth {
            get {
                return ResourceManager.GetString("StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік початку.
        /// </summary>
        public static string StartYear {
            get {
                return ResourceManager.GetString("StartYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фільми і серіали.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянути лог.
        /// </summary>
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переглянутий.
        /// </summary>
        public static string Watched {
            get {
                return ResourceManager.GetString("Watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рік є обов&apos;язковим.
        /// </summary>
        public static string YearRequired {
            get {
                return ResourceManager.GetString("YearRequired", resourceCulture);
            }
        }
    }
}
