//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cineaste.Client.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Problems {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Problems() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cineaste.Client.Localization.Problems", typeof(Problems).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user&apos;s list ID claim is invalid.
        /// </summary>
        public static string _problem_claim_list_id_invalid {
            get {
                return ResourceManager.GetString("/problem/claim/list-id/invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current user&apos;s list ID claim is missing.
        /// </summary>
        public static string _problem_claim_list_id_missing {
            get {
                return ResourceManager.GetString("/problem/claim/list-id/missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource was not found.
        /// </summary>
        public static string _problem_not_found {
            get {
                return ResourceManager.GetString("/problem/not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise not found.
        /// </summary>
        public static string _problem_not_found_franchise {
            get {
                return ResourceManager.GetString("/problem/not-found/franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise item not found.
        /// </summary>
        public static string _problem_not_found_franchise_item {
            get {
                return ResourceManager.GetString("/problem/not-found/franchise-item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise items not found.
        /// </summary>
        public static string _problem_not_found_franchise_items {
            get {
                return ResourceManager.GetString("/problem/not-found/franchise-items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List not found.
        /// </summary>
        public static string _problem_not_found_list {
            get {
                return ResourceManager.GetString("/problem/not-found/list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List item not found.
        /// </summary>
        public static string _problem_not_found_list_item {
            get {
                return ResourceManager.GetString("/problem/not-found/list-item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie not found.
        /// </summary>
        public static string _problem_not_found_movie {
            get {
                return ResourceManager.GetString("/problem/not-found/movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie kind not found.
        /// </summary>
        public static string _problem_not_found_movie_kind {
            get {
                return ResourceManager.GetString("/problem/not-found/movie-kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Franchise poster not found.
        /// </summary>
        public static string _problem_not_found_poster_franchise {
            get {
                return ResourceManager.GetString("/problem/not-found/poster/franchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie poster not found.
        /// </summary>
        public static string _problem_not_found_poster_movie {
            get {
                return ResourceManager.GetString("/problem/not-found/poster/movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season poster not found.
        /// </summary>
        public static string _problem_not_found_poster_season {
            get {
                return ResourceManager.GetString("/problem/not-found/poster/season", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series poster not found.
        /// </summary>
        public static string _problem_not_found_poster_series {
            get {
                return ResourceManager.GetString("/problem/not-found/poster/series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special episode poster not found.
        /// </summary>
        public static string _problem_not_found_poster_special_episode {
            get {
                return ResourceManager.GetString("/problem/not-found/poster/special-episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series not found.
        /// </summary>
        public static string _problem_not_found_series {
            get {
                return ResourceManager.GetString("/problem/not-found/series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series kind not found.
        /// </summary>
        public static string _problem_not_found_series_kind {
            get {
                return ResourceManager.GetString("/problem/not-found/series-kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Series period not found.
        /// </summary>
        public static string _problem_not_found_series_period {
            get {
                return ResourceManager.GetString("/problem/not-found/series/period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special episode not found.
        /// </summary>
        public static string _problem_not_found_series_special_episode {
            get {
                return ResourceManager.GetString("/problem/not-found/series/special-episode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        /// </summary>
        public static string _problem_not_implemented {
            get {
                return ResourceManager.GetString("/problem/not-implemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster fetch error.
        /// </summary>
        public static string _problem_poster {
            get {
                return ResourceManager.GetString("/problem/poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful response when fetching a poster.
        /// </summary>
        public static string _problem_poster_fetch {
            get {
                return ResourceManager.GetString("/problem/poster/fetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image URL is not found in the IMDb media page.
        /// </summary>
        public static string _problem_poster_imdb_media_image_not_found {
            get {
                return ResourceManager.GetString("/problem/poster/imdb-media/image/not-found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing poster content length.
        /// </summary>
        public static string _problem_poster_length_missing {
            get {
                return ResourceManager.GetString("/problem/poster/length/missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing poster content type.
        /// </summary>
        public static string _problem_poster_type_missing {
            get {
                return ResourceManager.GetString("/problem/poster/type/missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported poster type.
        /// </summary>
        public static string _problem_poster_type_unsupported {
            get {
                return ResourceManager.GetString("/problem/poster/type/unsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled problem has occurred.
        /// </summary>
        public static string _problem_unhandled {
            get {
                return ResourceManager.GetString("/problem/unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation has failed.
        /// </summary>
        public static string _problem_validation {
            get {
                return ResourceManager.GetString("/problem/validation", resourceCulture);
            }
        }
    }
}
